---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - sudo
    - mc
    - htop
#    - iftop
#    - iotop
    - git
    - ruby1.9.3
    - build-essential
    - python-software-properties
    - python-pycurl

#- name: Create symlink
#  file: src=/vagrant/applications/{{ project.name }}  dest=/var/www/{{ project.domain }} state=link
