---
php_packages:
   - php5-fpm
   - php5-cli
   - php5-pgsql
   - php5-mysql
   - php5-sqlite
   - php5-curl
   - php5-gd
   - php5-mcrypt
   - php5-memcached
   - php5-intl
   - php-pear
#  - php5-dev
   - php5-imagick
   - memcached